class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start3'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'list3'
        self.StatusCommand = 'status3'
        self.AuthorizedUsersCommand = 'users3'
        self.AuthorizeCommand = 'authorize3'
        self.UnAuthorizeCommand = 'unauthorize3'
        self.AddSudoCommand = 'addsudo3'
        self.RmSudoCommand = 'rmsudo3'
        self.PingCommand = 'ping3'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats3'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log3'
        self.SpeedCommand = 'speedtest3'
        self.CloneCommand = 'clone3'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del3'
        self.UsageCommand = 'usage3'

BotCommands = _BotCommands()
